DP\ProfileBundle\Entity\Profile:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    email:
      expose: true
    firstName:
      expose: true
      serialized_name: firstName
    lastName:
      expose: true
      serialized_name: lastName
    phone:
      expose: true
